---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Example python-kopf-s2i build
  name: python-kopf-s2i-example-build

parameters:
- name: FROM_IMAGE
  value: quay.io/jkupferer/python-kopf-s2i:latest
- name: GIT_REPO
  value: https://github.com/jkupferer/python-kopf-s2i-example.git
- name: NAME
  value: python-kopf-s2i-example

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: ${FROM_IMAGE}
        forcePull: true 
    triggers: []
